WebApp_MVC_L63_DB_Apprch_Mstr_2623/WebApp_MVC_L63_DB_Apprch_Mstr_2623/Areas/JobRecruiter/Controllers/RecruiterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp_MVC_L63_DB_Apprch_Mstr_2623.Models;

namespace WebApp_MVC_L63_DB_Apprch_Mstr_2623.Areas.JobRecruiter.Controllers
{
    public class RecruiterController : Controller
    {
        DatabaseContext db = new DatabaseContext();
        public ActionResult RecruiterHome()
        {
            int Rcidd = Convert.ToInt32(Session["Rcid"]);
            var data = (from a in db.tblJobRecruiters where a.JobRecruiter_id == Rcidd select a).ToList();
            return View(data);
        }
    }
}

WebApp_MVC_L63_DB_Apprch_Mstr_2623/WebApp_MVC_L63_DB_Apprch_Mstr_2623/Areas/JobRecruiter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Naukri.Com", "RecruiterHome", "Recruiter", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "RecruiterHome", "Recruiter", new { area = "JobRecruiter" })</li>
                </ul>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>