WebApp_MVC_Code_L62_ChngePas_6123/WebApp_MVC_Code_L62_ChngePas_6123/Controllers/Home1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp_MVC_Code_L62_ChngePas_6123.Models;

namespace WebApp_MVC_Code_L62_ChngePas_6123.Controllers
{
    public class Home1Controller : Controller
    {

        DatabaseContext db = new DatabaseContext();
        public ActionResult UserHome()
        {
            var ID = Convert.ToInt32(Session["IDD"]);
            var data = (from a in db.tblRegistrations
                        join b in db.tblCountries on a.country equals b.cid
                        where a.rid == ID
                        select new Join
                        {
                            rid = a.rid,
                            Name = a.Name,
                            Email = a.Email,
                            Password = a.Password,
                            Age = a.Age,
                            Countryname = b.cname
                        }).ToList();
            return View(data);

        }

       
        public ActionResult ChangePassword()
        {       
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(ChangePassword cp)
        {
            int ID = Convert.ToInt32(Session["IDD"]);
            //var data = (from a in db.tblRegistrations where a.rid == ID select a).ToList();
            tblRegistration data = db.tblRegistrations.Find(ID);
            if (data.Password == cp.OldPassword)
            {
                data.Password = cp.NewPassword;
                db.Entry(data).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                ViewBag.msgnew = "your password has been changed successfully !!";
            }
            else
            {
                ViewBag.msgold = "old passowrd didn't match, please enter correct password !!";
            }
            return View();
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("LoginForm", "Login");
        }

    }
}

WebApp_MVC_Code_L62_ChngePas_6123/WebApp_MVC_Code_L62_ChngePas_6123/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp_MVC_Code_L62_ChngePas_6123.Models;

namespace WebApp_MVC_Code_L62_ChngePas_6123.Controllers
{
    public class RegistrationController : Controller
    {
        DatabaseContext db = new DatabaseContext();
        public ActionResult RegistrationForm(int id = 0)
        {

            tblRegistration obj = new tblRegistration();
            ViewBag.bt = "Save";
            if (id > 0)
            {
                var data = (from a in db.tblRegistrations where a.rid == id select a).ToList();
                obj.rid = data[0].rid;
                obj.Name = data[0].Name;
                obj.Email = data[0].Email;
                obj.Password = data[0].Password;
                obj.Age = data[0].Age;
                obj.country = data[0].country;
                ViewBag.bt = "Update";

            }
            ViewBag.ctr = db.tblCountries.ToList();
            return View(obj);
        }

        [HttpPost]
        public ActionResult RegistrationForm(tblRegistration obj)
        {
            //if (obj.rid > 0)
            //{
            //    db.Entry(obj).State = System.Data.Entity.EntityState.Modified;
            //}
            //else
            //{
            //    if (ModelState.IsValid)
            //    {
            //        db.tblRegistrations.Add(obj);

            //        //return RedirectToAction("RegistrationDisplay");
            //    }
            //    else
            //    {
            //        return View();
            //    }
            //}
            //return View();
            //db.SaveChanges();
            //return RedirectToAction("RegistrationDisplay");

            //sir logic
            if (ModelState.IsValid)
            {
                if (obj.rid > 0)
                {
                    db.Entry(obj).State = System.Data.Entity.EntityState.Modified;
                }
                else
                {
                    db.tblRegistrations.Add(obj);
                }
                db.SaveChanges();
                return RedirectToAction("RegistrationDisplay");
            }
            else
            {
                return View();
            }



        }


        public ActionResult RegistrationDisplay()
        {
            //var data = (from a in db.tblRegistrations select a).ToList();
            var data = (from a in db.tblRegistrations
                        join b in db.tblCountries on a.country equals b.cid
                        select new Join
                        {
                            rid = a.rid,
                            Name = a.Name,
                            Email = a.Email,
                            Password = a.Password,
                            Age = a.Age,
                            Countryname = b.cname
                        }).ToList();
            return View(data);
        }

        public ActionResult Delete(int id = 0)
        {
            var data = db.tblRegistrations.Find(id);
            db.tblRegistrations.Remove(data);
            db.SaveChanges();
            return RedirectToAction("RegistrationDisplay");
        }
    }
}

WebApp_MVC_Code_L62_ChngePas_6123/WebApp_MVC_Code_L62_ChngePas_6123/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Naukri.Com", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Registration Form", "RegistrationForm", "Registration")</li>
                    <li>@Html.ActionLink("Display", "RegistrationDisplay", "Registration")</li>
                    <li>@Html.ActionLink("Login", "LoginForm", "Login")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br/>
        <br/>
        <br/>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApp_MVC_Code_L62_ChngePas_6123/WebApp_MVC_Code_L62_ChngePas_6123/Views/Shared/_Layout1.cshtml
@{
    ViewBag.Title = "_Layout1";
   
}



<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Naukri.Com", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("User Home", "UserHome", "Home1")</li>
                    <li>@Html.ActionLink("Change Password", "ChangePassword", "Home1")</li>
                    <li>@Html.ActionLink("Logout", "Logout", "Home1")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br />
        <br />
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>